"""
Copyright 2018-2019 Telenav (http://telenav.com)

This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at http://mozilla.org/MPL/2.0/.
"""
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orbb_localization.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import orbb_metadata_pb2 as orbb__metadata__pb2
import orbb_definitions_pb2 as orbb__definitions__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='orbb_localization.proto',
  package='orbb',
  syntax='proto2',
  serialized_pb=_b('\n\x17orbb_localization.proto\x12\x04orbb\x1a\x13orbb_metadata.proto\x1a\x16orbb_definitions.proto\"\x9e\x01\n\tRoiFromDB\x12\x16\n\x03roi\x18\x01 \x02(\x0b\x32\t.orbb.Roi\x12\x0e\n\x06roi_id\x18\x02 \x02(\x03\x12\x0f\n\x07trip_id\x18\x03 \x02(\x03\x12\x1f\n\x08location\x18\x04 \x02(\x0b\x32\r.orbb.GPSPair\x12\x12\n\ncluster_id\x18\x05 \x01(\x03\x12\x11\n\tseq_index\x18\x06 \x01(\t\x12\x10\n\x08platform\x18\x07 \x01(\t\"o\n\x0cLocalizedRoi\x12\x18\n\x04type\x18\x01 \x02(\x0e\x32\n.orbb.Mark\x12\x1f\n\x08location\x18\x02 \x02(\x0b\x32\r.orbb.GPSPair\x12\x0e\n\x06\x66\x61\x63ing\x18\x03 \x02(\x02\x12\x14\n\x0cused_roi_ids\x18\x04 \x03(\x03\"0\n\x08RoiSetDB\x12$\n\x0broi_from_db\x18\x01 \x03(\x0b\x32\x0f.orbb.RoiFromDB\"\xd0\x01\n\x0e\x43lusteredPoint\x12\x12\n\ncluster_id\x18\x01 \x02(\x03\x12\x1f\n\x08location\x18\x02 \x02(\x0b\x32\r.orbb.GPSPair\x12\x0e\n\x06\x66\x61\x63ing\x18\x03 \x02(\x02\x12\x18\n\x04type\x18\x04 \x02(\x0e\x32\n.orbb.Mark\x12\x11\n\tnb_points\x18\x05 \x02(\r\x12\x12\n\nconfidence\x18\x06 \x02(\x02\x12\'\n\x10matched_location\x18\x07 \x01(\x0b\x32\r.orbb.GPSPair\x12\x0f\n\x07roi_ids\x18\x08 \x03(\r\"1\n\x08\x43lusters\x12%\n\x07\x63luster\x18\x01 \x03(\x0b\x32\x14.orbb.ClusteredPoint')
  ,
  dependencies=[orbb__metadata__pb2.DESCRIPTOR,orbb__definitions__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ROIFROMDB = _descriptor.Descriptor(
  name='RoiFromDB',
  full_name='orbb.RoiFromDB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='roi', full_name='orbb.RoiFromDB.roi', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='roi_id', full_name='orbb.RoiFromDB.roi_id', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trip_id', full_name='orbb.RoiFromDB.trip_id', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='location', full_name='orbb.RoiFromDB.location', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cluster_id', full_name='orbb.RoiFromDB.cluster_id', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seq_index', full_name='orbb.RoiFromDB.seq_index', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='platform', full_name='orbb.RoiFromDB.platform', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=237,
)


_LOCALIZEDROI = _descriptor.Descriptor(
  name='LocalizedRoi',
  full_name='orbb.LocalizedRoi',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='orbb.LocalizedRoi.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=32,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='location', full_name='orbb.LocalizedRoi.location', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='facing', full_name='orbb.LocalizedRoi.facing', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='used_roi_ids', full_name='orbb.LocalizedRoi.used_roi_ids', index=3,
      number=4, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=239,
  serialized_end=350,
)


_ROISETDB = _descriptor.Descriptor(
  name='RoiSetDB',
  full_name='orbb.RoiSetDB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='roi_from_db', full_name='orbb.RoiSetDB.roi_from_db', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=352,
  serialized_end=400,
)


_CLUSTEREDPOINT = _descriptor.Descriptor(
  name='ClusteredPoint',
  full_name='orbb.ClusteredPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cluster_id', full_name='orbb.ClusteredPoint.cluster_id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='location', full_name='orbb.ClusteredPoint.location', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='facing', full_name='orbb.ClusteredPoint.facing', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='orbb.ClusteredPoint.type', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=32,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nb_points', full_name='orbb.ClusteredPoint.nb_points', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='orbb.ClusteredPoint.confidence', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='matched_location', full_name='orbb.ClusteredPoint.matched_location', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='roi_ids', full_name='orbb.ClusteredPoint.roi_ids', index=7,
      number=8, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=403,
  serialized_end=611,
)


_CLUSTERS = _descriptor.Descriptor(
  name='Clusters',
  full_name='orbb.Clusters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cluster', full_name='orbb.Clusters.cluster', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=613,
  serialized_end=662,
)

_ROIFROMDB.fields_by_name['roi'].message_type = orbb__metadata__pb2._ROI
_ROIFROMDB.fields_by_name['location'].message_type = orbb__metadata__pb2._GPSPAIR
_LOCALIZEDROI.fields_by_name['type'].enum_type = orbb__definitions__pb2._MARK
_LOCALIZEDROI.fields_by_name['location'].message_type = orbb__metadata__pb2._GPSPAIR
_ROISETDB.fields_by_name['roi_from_db'].message_type = _ROIFROMDB
_CLUSTEREDPOINT.fields_by_name['location'].message_type = orbb__metadata__pb2._GPSPAIR
_CLUSTEREDPOINT.fields_by_name['type'].enum_type = orbb__definitions__pb2._MARK
_CLUSTEREDPOINT.fields_by_name['matched_location'].message_type = orbb__metadata__pb2._GPSPAIR
_CLUSTERS.fields_by_name['cluster'].message_type = _CLUSTEREDPOINT
DESCRIPTOR.message_types_by_name['RoiFromDB'] = _ROIFROMDB
DESCRIPTOR.message_types_by_name['LocalizedRoi'] = _LOCALIZEDROI
DESCRIPTOR.message_types_by_name['RoiSetDB'] = _ROISETDB
DESCRIPTOR.message_types_by_name['ClusteredPoint'] = _CLUSTEREDPOINT
DESCRIPTOR.message_types_by_name['Clusters'] = _CLUSTERS

RoiFromDB = _reflection.GeneratedProtocolMessageType('RoiFromDB', (_message.Message,), dict(
  DESCRIPTOR = _ROIFROMDB,
  __module__ = 'orbb_localization_pb2'
  # @@protoc_insertion_point(class_scope:orbb.RoiFromDB)
  ))
_sym_db.RegisterMessage(RoiFromDB)

LocalizedRoi = _reflection.GeneratedProtocolMessageType('LocalizedRoi', (_message.Message,), dict(
  DESCRIPTOR = _LOCALIZEDROI,
  __module__ = 'orbb_localization_pb2'
  # @@protoc_insertion_point(class_scope:orbb.LocalizedRoi)
  ))
_sym_db.RegisterMessage(LocalizedRoi)

RoiSetDB = _reflection.GeneratedProtocolMessageType('RoiSetDB', (_message.Message,), dict(
  DESCRIPTOR = _ROISETDB,
  __module__ = 'orbb_localization_pb2'
  # @@protoc_insertion_point(class_scope:orbb.RoiSetDB)
  ))
_sym_db.RegisterMessage(RoiSetDB)

ClusteredPoint = _reflection.GeneratedProtocolMessageType('ClusteredPoint', (_message.Message,), dict(
  DESCRIPTOR = _CLUSTEREDPOINT,
  __module__ = 'orbb_localization_pb2'
  # @@protoc_insertion_point(class_scope:orbb.ClusteredPoint)
  ))
_sym_db.RegisterMessage(ClusteredPoint)

Clusters = _reflection.GeneratedProtocolMessageType('Clusters', (_message.Message,), dict(
  DESCRIPTOR = _CLUSTERS,
  __module__ = 'orbb_localization_pb2'
  # @@protoc_insertion_point(class_scope:orbb.Clusters)
  ))
_sym_db.RegisterMessage(Clusters)


# @@protoc_insertion_point(module_scope)
